### ISSUE TITLE
Issue with pretrained module 

### ISSUE THREAD

**Issue by Elfilali-Taoufiq** [gabrielStanovsky/supervised_oie_wrapper#4]
when i Run the run_oie script, I find this problem 

Traceback (most recent call last):
  File "run_oie.py", line 12, in <module>
    from allennlp.pretrained import open_information_extraction_stanovsky_2018
ModuleNotFoundError: No module named 'allennlp.pretrained'

whish AllenNLP version I should use ?

**Comment by taylormr** [comment]
#3
